### ISSUE TITLE
Render error when running test

### ISSUE THREAD

**Issue by Nerian** [r7kamura/slimi#9]
Hi,

Given a slim template with the following content:

```
ruby:
  'hello'
```

I get the following error:

```
# /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:15:in `on_slimi_interpolate'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:70:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `each'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:116:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:69:in `replace_dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:55:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:45:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:11:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:132:in `collect_text'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:234:in `on_slimi_embedded'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:111:in `on_slimi_embedded'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:70:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `each'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:114:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:69:in `replace_dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:55:in `dispatcher'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:49:in `compile'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/mixins/dispatcher.rb:45:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/engine.rb:50:in `block in call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/engine.rb:50:in `each'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/engine.rb:50:in `inject'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/temple-0.10.0/lib/temple/engine.rb:50:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/rails_template_handler.rb:30:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/rails_template_handler.rb:13:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/wicked_pdf-2.6.3/lib/wicked_pdf/pdf_helper.rb:18:in `render'
     # ./apps/mis/app/controllers/mis/tools/school_details/my_schools_controller.rb:13:in `show'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/i18n-1.8.11/lib/i18n.rb:314:in `with_locale'
     # ./apps/mis/app/controllers/mis/base_controller.rb:40:in `set_locale'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/marginalia-1.11.1/lib/marginalia.rb:109:in `record_query_comment'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/actiontext-7.0.4.2/lib/action_text/rendering.rb:20:in `with_renderer'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/actiontext-7.0.4.2/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:530:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/railtie.rb:226:in `public_send'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/railtie.rb:226:in `method_missing'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:314:in `mock_call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:189:in `call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:314:in `mock_call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:189:in `call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:314:in `mock_call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:189:in `call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:314:in `mock_call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:189:in `call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:314:in `mock_call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:189:in `call!'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/omniauth-2.1.1/lib/omniauth/builder.rb:44:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/bullet-7.0.7/lib/bullet/rack.rb:14:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/makara-0.5.1/lib/makara/middleware.rb:16:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/tempfile_reaper.rb:15:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-steady_etag-0.3.2/lib/rack/steady_etag.rb:43:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/deflater.rb:44:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/conditional_get.rb:27:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/head.rb:12:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:266:in `context'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:260:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/bugsnag-6.25.2/lib/bugsnag/integrations/rack.rb:51:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/chewy-7.2.7/lib/chewy/railtie.rb:21:in `block in call'
     # /Users/Nerian/satchel/show-app/backend/shared/gems/smhw-business-logic/shared_spec/support/chewy.rb:41:in `block in stub_elasticsearch_requests'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/chewy-7.2.7/lib/chewy/railtie.rb:21:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/rack/logger.rb:40:in `call_app'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/rack/logger.rb:25:in `block in call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/rack/logger.rb:25:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/method_override.rb:24:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/runtime.rb:22:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-2.2.6.2/lib/rack/sendfile.rb:110:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/railties-7.0.4.2/lib/rails/engine.rb:530:in `call'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-test-2.0.2/lib/rack/test.rb:358:in `process_request'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rack-test-2.0.2/lib/rack/test.rb:155:in `request'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
     # ./spec/requests/mis/tools/school_details/my_schools_controller_spec.rb:6:in `block (3 levels) in <main>'
     # ./spec/support/mis/request_test.rb:63:in `block (2 levels) in <main>'
     # ./spec/rails_helper.rb:65:in `block (3 levels) in <top (required)>'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/i18n-1.8.11/lib/i18n.rb:314:in `with_locale'
     # ./spec/rails_helper.rb:64:in `block (2 levels) in <top (required)>'
     # ./spec/support/request_api_version.rb:7:in `block (2 levels) in <main>'
     # /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   wrong number of arguments (given 3, expected 1)
     #   /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:15:in `on_slimi_interpolate'
```

This only happens when running the test suite. This it s a Rails request test. In the development environment the page renders correctly without error. I disabled layouts and any other template, I get this error merely rendering the code as shown.

I added a binding.pry on the source so as to see what the method is receiving:

```
From: /Users/Nerian/.rvm/gems/ruby-3.2.0/gems/slimi-0.7.2/lib/slimi/filters/embedded.rb:16 Slimi::Filters::TextCollector#on_slimi_interpolate:

    15: def on_slimi_interpolate(text, o = nil, a = nil)
 => 16:   binding.pry
    17:   @collected << text
    18:   nil
    19: end

[1] pry(#<Slimi::Filters::TextCollector>)> [text, o, a]
=> [524, 531, "'hello'"]
```

I added the `, o = nil, a = nil` so that it doesn't fail. Perhaps the signature of this method should be changed?

**Comment by Nerian** [comment]
`temple` was updated on Jan 23. Perhaps something changed that affected this?

https://github.com/judofyr/temple/compare/v0.9.1...v0.10.0

**Comment by r7kamura** [comment]
Thanks for reporting. It's been a while since I looked into temple's API, so I won't know right away, but I'll look into the cause 👀

**Comment by Nerian** [comment]
I tested this and it works fine. Solves the issue 👨‍🍳

**Comment by Nerian** [comment]
Although one more thing I noticed is that when a given template contains multiple errors, they are not all auto corrected. Some times I need to run `rubocop -A` multiple times so auto solve all issues; this was happening the change to slimi so it is unrelated . Will open a new issue for this.

**Comment by r7kamura** [comment]
Thanks, I will merge #11 for now and release a new version.

**Comment by Nerian** [comment]
Hold on, I think we still are missing some edge case. I get this in some cases. Will get you a backtrace in a moment.

```
ActionView::Template::Error:
       can't modify frozen String: ""
```

**Comment by Nerian** [comment]
Found the issue:

```
# frozen_string_literal: true

require 'tilt'

module Slimi
  module Filters
    # @api private
    class TextCollector < Base
      def call(exp)
        @collected = ''
        super(exp)
        @collected
      end

      def on_slimi_interpolate(_, _, text)
        @collected << text
        nil
      end
    end
```

That `# frozen_string_literal: true` at the top makes it so that can't to the `@collected << test` , because the string is frozen . Removing that line solves the issue with 'can't modify frozen String'.

But, there is more:

Given a template with:

```
ruby:
  title      = 5
  title      = 5
```

I get the following error:
```
     # SyntaxError:
     #   /Users/Nerian/satchel/show-app/backend/smhw-api/apps/mis/app/views/mis/documents/imports/index.html.slim:2: syntax error, unexpected local variable or method, expecting `end' or dummy end
     #   ; title      = 5title      = 5
```

If I understand this correctly, this happens due to the concatenation here, right?
```
def on_slimi_interpolate(_, _, text)
  @collected << text
  nil
end
```

I fixed this by adding a `;`
```
def on_slimi_interpolate(_, _, text)
  @collected << "#{text};"
  nil
end
```

Not sure if this si the best solution.

**Comment by r7kamura** [comment]
Hmm, actually, I have just imitated slim gem's implementation in this area, and I don't know much about it yet. I'll look into the implementation a bit more.

- https://github.com/slim-template/slim/blob/main/lib/slim/embedded.rb

First, I'll fix the FrozenError in the following Pull Request:

- https://github.com/r7kamura/slimi/pull/13

**Comment by Nerian** [comment]
Tried the new release. I get this error:

     ActionView::SyntaxErrorInTemplate:
       Encountered a syntax error while rendering template: check ruby:
         title      = 5
         title      = 5

    # ./apps/mis/app/views/layouts/mis/application.html.slim:2: syntax error, unexpected local variable or method, expecting `end' or dummy end
     # ; title      = 5title      = 5

The layout is just:
```
ruby:
  title      = 5
  title      = 5
```

So it's like multiple lines of ruby code are not correctly interpreted.

**Comment by Nerian** [comment]
Tried today again. But still same error.Multiple lines of embedded ruby code are concatenated together and raises syntax error
